#!/bin/sh
COMPOJURE_HOME=compojure
CLASSPATH=src:$COMPOJURE_HOME/compojure.jar
 
for f in $COMPOJURE_HOME/deps/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done

for f in ./lib/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done
 
java -cp $CLASSPATH clojure.lang.Script src/corfox/q3/site.clj
